services:
  frankenphp:
    build:
      context: .
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./.env:/app/.env
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    restart: unless-stopped
