services:
  frankenphp:
    build:
      context: .
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    entrypoint: >
      sh -c "composer install && npm i && npm run build && php artisan storage:link && exec php artisan octane:frankenphp --workers=1 --max-requests=1"